/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServiceAreasRouteImport } from './routes/service-areas'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesTruckRecoveryRouteImport } from './routes/services/truck-recovery'
import { Route as ServicesMachineRecoveryRouteImport } from './routes/services/machine-recovery'
import { Route as ServicesFlatTyresRouteImport } from './routes/services/flat-tyres'
import { Route as ServicesCarRecoveryRouteImport } from './routes/services/car-recovery'
import { Route as ServicesBikeRecoveryRouteImport } from './routes/services/bike-recovery'
import { Route as ServicesBatteryJumpStartRouteImport } from './routes/services/battery-jump-start'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasRoute = ServiceAreasRouteImport.update({
  id: '/service-areas',
  path: '/service-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesTruckRecoveryRoute = ServicesTruckRecoveryRouteImport.update({
  id: '/services/truck-recovery',
  path: '/services/truck-recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMachineRecoveryRoute = ServicesMachineRecoveryRouteImport.update({
  id: '/services/machine-recovery',
  path: '/services/machine-recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesFlatTyresRoute = ServicesFlatTyresRouteImport.update({
  id: '/services/flat-tyres',
  path: '/services/flat-tyres',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCarRecoveryRoute = ServicesCarRecoveryRouteImport.update({
  id: '/services/car-recovery',
  path: '/services/car-recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBikeRecoveryRoute = ServicesBikeRecoveryRouteImport.update({
  id: '/services/bike-recovery',
  path: '/services/bike-recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBatteryJumpStartRoute =
  ServicesBatteryJumpStartRouteImport.update({
    id: '/services/battery-jump-start',
    path: '/services/battery-jump-start',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/service-areas': typeof ServiceAreasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/services/battery-jump-start': typeof ServicesBatteryJumpStartRoute
  '/services/bike-recovery': typeof ServicesBikeRecoveryRoute
  '/services/car-recovery': typeof ServicesCarRecoveryRoute
  '/services/flat-tyres': typeof ServicesFlatTyresRoute
  '/services/machine-recovery': typeof ServicesMachineRecoveryRoute
  '/services/truck-recovery': typeof ServicesTruckRecoveryRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/service-areas': typeof ServiceAreasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/services/battery-jump-start': typeof ServicesBatteryJumpStartRoute
  '/services/bike-recovery': typeof ServicesBikeRecoveryRoute
  '/services/car-recovery': typeof ServicesCarRecoveryRoute
  '/services/flat-tyres': typeof ServicesFlatTyresRoute
  '/services/machine-recovery': typeof ServicesMachineRecoveryRoute
  '/services/truck-recovery': typeof ServicesTruckRecoveryRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/service-areas': typeof ServiceAreasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/services/battery-jump-start': typeof ServicesBatteryJumpStartRoute
  '/services/bike-recovery': typeof ServicesBikeRecoveryRoute
  '/services/car-recovery': typeof ServicesCarRecoveryRoute
  '/services/flat-tyres': typeof ServicesFlatTyresRoute
  '/services/machine-recovery': typeof ServicesMachineRecoveryRoute
  '/services/truck-recovery': typeof ServicesTruckRecoveryRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/faqs'
    | '/gallery'
    | '/privacy-policy'
    | '/service-areas'
    | '/sitemap.xml'
    | '/terms'
    | '/services/battery-jump-start'
    | '/services/bike-recovery'
    | '/services/car-recovery'
    | '/services/flat-tyres'
    | '/services/machine-recovery'
    | '/services/truck-recovery'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faqs'
    | '/gallery'
    | '/privacy-policy'
    | '/service-areas'
    | '/sitemap.xml'
    | '/terms'
    | '/services/battery-jump-start'
    | '/services/bike-recovery'
    | '/services/car-recovery'
    | '/services/flat-tyres'
    | '/services/machine-recovery'
    | '/services/truck-recovery'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/faqs'
    | '/gallery'
    | '/privacy-policy'
    | '/service-areas'
    | '/sitemap.xml'
    | '/terms'
    | '/services/battery-jump-start'
    | '/services/bike-recovery'
    | '/services/car-recovery'
    | '/services/flat-tyres'
    | '/services/machine-recovery'
    | '/services/truck-recovery'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FaqsRoute: typeof FaqsRoute
  GalleryRoute: typeof GalleryRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ServiceAreasRoute: typeof ServiceAreasRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ServicesBatteryJumpStartRoute: typeof ServicesBatteryJumpStartRoute
  ServicesBikeRecoveryRoute: typeof ServicesBikeRecoveryRoute
  ServicesCarRecoveryRoute: typeof ServicesCarRecoveryRoute
  ServicesFlatTyresRoute: typeof ServicesFlatTyresRoute
  ServicesMachineRecoveryRoute: typeof ServicesMachineRecoveryRoute
  ServicesTruckRecoveryRoute: typeof ServicesTruckRecoveryRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas': {
      id: '/service-areas'
      path: '/service-areas'
      fullPath: '/service-areas'
      preLoaderRoute: typeof ServiceAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/truck-recovery': {
      id: '/services/truck-recovery'
      path: '/services/truck-recovery'
      fullPath: '/services/truck-recovery'
      preLoaderRoute: typeof ServicesTruckRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/machine-recovery': {
      id: '/services/machine-recovery'
      path: '/services/machine-recovery'
      fullPath: '/services/machine-recovery'
      preLoaderRoute: typeof ServicesMachineRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/flat-tyres': {
      id: '/services/flat-tyres'
      path: '/services/flat-tyres'
      fullPath: '/services/flat-tyres'
      preLoaderRoute: typeof ServicesFlatTyresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/car-recovery': {
      id: '/services/car-recovery'
      path: '/services/car-recovery'
      fullPath: '/services/car-recovery'
      preLoaderRoute: typeof ServicesCarRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/bike-recovery': {
      id: '/services/bike-recovery'
      path: '/services/bike-recovery'
      fullPath: '/services/bike-recovery'
      preLoaderRoute: typeof ServicesBikeRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/battery-jump-start': {
      id: '/services/battery-jump-start'
      path: '/services/battery-jump-start'
      fullPath: '/services/battery-jump-start'
      preLoaderRoute: typeof ServicesBatteryJumpStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FaqsRoute: FaqsRoute,
  GalleryRoute: GalleryRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ServiceAreasRoute: ServiceAreasRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ServicesBatteryJumpStartRoute: ServicesBatteryJumpStartRoute,
  ServicesBikeRecoveryRoute: ServicesBikeRecoveryRoute,
  ServicesCarRecoveryRoute: ServicesCarRecoveryRoute,
  ServicesFlatTyresRoute: ServicesFlatTyresRoute,
  ServicesMachineRecoveryRoute: ServicesMachineRecoveryRoute,
  ServicesTruckRecoveryRoute: ServicesTruckRecoveryRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
